version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3

jobs:
  lint_and_test:
    machine:
      image: ubuntu-2004:202010-01

    working_directory: ~/Anzu

    steps:
      - checkout
      - run:
          name: Check Node version
          command: node --version
      - restore_cache:
          keys:
            - v1-npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-npm-deps-{{ .Branch }}
            - v1-npm-deps-
      - run:
          name: Resolve all dependencies
          command: npm ci
      - save_cache:
          key: v1-npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - 'node_modules'
      - run:
          name: Format the code
          command: npm run format
      - run:
          name: Lint to check for errors
          command: npm run lint

  deploy:
    executor: heroku/default

    working_directory: ~/Anzu

    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  heroku_deploy_with_tests:
    jobs:
      - lint_and_test
      - deploy:
          requires:
            - lint_and_test
          filters:
            branches:
              only:
                - master
