name: Node.js

on:
  pull_request:
    branches: [main]

jobs:
  quality-check:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Check circular dependencies
        run: yarn circular-check

      - name: Format, lint, and type-check
        run: yarn lint
